package com.kote.taskifyapp

const val KEY_TITLE = "KEY_TITLE"
const val KEY_DESCRIPTION = "KEY_DESCRIPTION"
const val CHANNEL_ID = "VERBOSE_NOTIFICATION"
const val TASK_ID = "TASK_ID"
const val NOTIFICATION = "NOTIFICATION"
const val OVERDUE_NOTIFICATION_ID = 1000
const val CLEANUP = "CLEANUP"
const val ACTIVE_NOTIFICATION_ALARM = "ACTIVE_NOTIFICATION_ALARM"
const val OVERDUE_NOTIFICATION_ALARM = "OVERDUE_NOTIFICATION_ALARM"
const val DELAY_FOR_DELETE = 30L * 24 * 60 * 60 * 1000
//const val DELAY_FOR_DELETE = 60000L
val CHANNEL_NAME: CharSequence = "Reminder Notifications"